pipeline {
    agent any

    stages {
        stage('all repository') {
            steps {
                sh "cd /Final_project_DevOps_online_Kharkiv_2021Q4  | ls -la "
                echo "Building......."
                echo "End of Stage Build"
            }
        }
    }
}
